name: Publish CLI
on:
  push:
    branches:
      - "main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: "./CLI"
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - run: ls
      - run: cd CLI/CLI && ls
      - run: cd CLI/CLI && npm install
      - name: Create pull request or publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: cd CLI && npm run build
